### ISSUE TITLE
Could you update the newest version of AriaNg

### ISSUE THREAD

**Issue by PS0123456** [maple3142/aria2-manager#4]
RT

**Comment by maple3142** [comment]
Updated, but publishing to chrome and firefox takes time.
If you don't want to wait, just clone this repo and load it in the browser.

**Comment by maple3142** [comment]
Firefox version has been approved: https://addons.mozilla.org/en-US/firefox/addon/aria2-manager/

**Comment by PS0123456** [comment]
THX
